### ISSUE TITLE
FOOTER: add full width logo section

### ISSUE THREAD

**Issue by tmfrnz** [impactoss/impactoss-client#193]
@dmprk to provide layout
@ashbowe to provide logos, ideally in vector format

**Comment by tmfrnz** [comment]
![office_logo_en_black_large_300dpi](https://cloud.githubusercontent.com/assets/5811956/26382175/f5ba16a2-4086-11e7-962c-d448df228385.png)
![office_logo_en_blue_large_300dpi](https://cloud.githubusercontent.com/assets/5811956/26382176/f5bf09a0-4086-11e7-8d8d-62fd71765af0.png)
[UNDP-vector-logo-A588D076F4-seeklogo.com.zip](https://github.com/dumparkltd/hr-nmrf-client/files/1024094/UNDP-vector-logo-A588D076F4-seeklogo.com.zip)

**Comment by ashbowe** [comment]
![nz logo](https://cloud.githubusercontent.com/assets/21161841/26423295/a02e812a-4129-11e7-9ebd-bfd013d7767e.jpg)

**Comment by ashbowe** [comment]
This was the only format they provided I'm afraid!

**Comment by dmprk** [comment]
![footer.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/556cf58fb094e61c00764138/125516c66e82c728ace21e0d46ee9b95378791ebc3abaf51ab57f5973d047d317c5cfa292880e52ce61222595e5e1daf41580943aff08a22b4aa2e32db025fb28c341521842f1bbebb8315be04ba20884c83bebb8d45c6ea2f68.png)

**Comment by ashbowe** [comment]
Looks good!
