### ISSUE TITLE
IMPORT: Allow batch importing of entities

### ISSUE THREAD

**Issue by tmfrnz** [impactoss/impactoss-client#225]

**Comment by tmfrnz** [comment]
- show parse error messages

**Comment by dmprk** [comment]
for wireframes see #248

**Comment by tmfrnz** [comment]
- [ ] limit filename length to prevent name overflowing component

**Comment by tmfrnz** [comment]
- [ ] consider adding error and success icons

**Comment by tmfrnz** [comment]
test
- [x] recommendations
- [x] indicators
- [x] actions
- [x] sdg targets
