### ISSUE TITLE
PAGES: Apply layout for editorial content/pages

### ISSUE THREAD

**Issue by tmfrnz** [impactoss/impactoss-client#229]

**Comment by dmprk** [comment]
![page.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/556cf58fb094e61c00764138/125516c66e82c728ace21e0d46f8959d26c0cfeb9ffbb049a15ee4d67304722b7006fb2e7681ba78e61a2a500c5c4eac175f0c4dfff09b37b4f46d2ede0356b49b381d66cc2f12adb2831abf01b9238c4f81b7b88a48d2a5.png)
