### ISSUE TITLE
MULTISELECT: Advanced filterable multiselect list component (recommendations, actions)

### ISSUE THREAD

**Issue by tmfrnz** [impactoss/impactoss-client#23]
_From @joshmcarthur on August 8, 2016 4:3_

As a user of Sadata

I want an easy to use UI element for filtering a large list of things by keyword and associated categories and choosing one or more options from the list.

---

Development tasks:
1. Implement partial structure for rendering list container
2. Implement generic-ish Javascript to perform XHR requests to populate the list
3. Allow filtering of the list using a search field
4. Consider supporting pagination
5. Support adding new record and selecting it from the list
6. If items are pre-selected, show them at the top of the list
7. Try not to put too much magic in

<img width="927" alt="screenshot 2016-08-08 16 05 13" src="https://cloud.githubusercontent.com/assets/292020/17469082/f9617eb4-5d81-11e6-8f4a-f765f0e7f277.png">

_Copied from original issue: dumparkltd/hr-nmrf-server#28_

**Comment by tmfrnz** [comment]
used for filtering principal entities (recommendations - actions - indicators) by principal entity and batch associating principal entities 

advanced version of #42,

**Comment by tmfrnz** [comment]
Assign core entities to single core entity (#26, #27, #32, #33) or to multiple other core entities from batch edit mode (#47, #48, #49, #50, #63, #64)

![action-new-6](https://cloud.githubusercontent.com/assets/5811956/20300160/b37abc68-ab82-11e6-8038-3c1fefd22f35.png)

![action-new-6](https://cloud.githubusercontent.com/assets/5811956/20299257/f97653b6-ab7e-11e6-9e9f-c0b500cff48c.png)

**Comment by tmfrnz** [comment]
Filter core entities by core entities
![screenshot 2016-11-15 22 01 15](https://cloud.githubusercontent.com/assets/5811956/20299293/331b4ffe-ab7f-11e6-90a8-e608815a0fab.png)

**Comment by tmfrnz** [comment]
Uses #28

**Comment by tmfrnz** [comment]
also allow  filtering list by common category

**Comment by dmprk** [comment]
![multiselect.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/556cf58fb094e61c00764138/125516c66e82c728ace21e0d46e58196378b90ac83ecbc57e611b2843b492d762a10e17132d0bb71bd1a7e070b564ea549595e17fff9897da1e53573834e17ff933c0120996048e6edc00db513b921814e80b6bc834ac3ec3525e2888b5d73.png)

**Comment by tmfrnz** [comment]
- [ ] changes hint should be lighter

**Comment by tmfrnz** [comment]
- [ ] consider opening multiselect panel in modal when editing single entities
- [ ] ensure only one multiselect panel is open when editing single entities
