### ISSUE TITLE
FORM: Improve user feedback messages

### ISSUE THREAD

**Issue by tmfrnz** [impactoss/impactoss-client#249]
### Progress/processing
- [x] loading
- [x] saving
- [x] uploading
- [x] importing
- [x] batch editing - indeterminate
- [x] batch editing - determinate

### Errors, warnings
- [x] server messages
- [ ] field validation

**Comment by dmprk** [comment]
![form-1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/556cf58fb094e61c00764138/125516c66e82c728ace21e0d46ee9b882ecfd2ebc3abaf51ab57f5973d047d317c5cfa292880e52ce61222595e5e1daf41580943aff08a22b4aa2e32db025fb28c341521842f1bbeba8415be05b3298a4c8db3bd8845c7ed2f68.png)
![form-2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/556cf58fb094e61c00764138/125516c66e82c728ace21e0d46ee9b882ecfd1ebc3abaf51ab57f5973d047d317c5cfa292880e52ce61222595e5e1daf41580943aff08a22b4aa2e32db025fb28c341521842f1bbebb8315be05b3298a4c8db3bd894cc6ed2f68.png)
![form-3.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/556cf58fb094e61c00764138/125516c66e82c728ace21e0d46ee9b882ecfd0ebc3abaf51ab57f5973d047d317c5cfa292880e52ce61222595e5e1daf41580943aff08a22b4aa2e32db025fb28c341521842f1bbeba8415be05b3298a4c8db3bd8845c8ea2f68.png)
![form-4.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/556cf58fb094e61c00764138/125516c66e82c728ace21e0d46ee9b882ecfd7ebc3abaf51ab57f5973d047d317c5cfa292880e52ce61222595e5e1daf41580943aff08a22b4aa2e32db025fb28c341521842f1bbeba8415be05b3298a4c8db3bd894cc8ef2f68.png)
![list-1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/556cf58fb094e61c00764138/125516c66e82c728ace21e0d46e49d8937cfd2ebc3abaf51ab57f5973d047d317c5cfa292880e52ce61222595e5e1daf41580943aff08a22b4aa2e32db025fb28c341521842f1bbeba8415be05b3298a4c8db3bd894cc3eb2f68.png)
![list-2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/556cf58fb094e61c00764138/125516c66e82c728ace21e0d46e49d8937cfd1ebc3abaf51ab57f5973d047d317c5cfa292880e52ce61222595e5e1daf41580943aff08a22b4aa2e32db025fb28c341521842f1bbebb8315be05b3298a4c8db3bd894ec3e02f68.png)
![list-3.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/556cf58fb094e61c00764138/125516c66e82c728ace21e0d46e49d8937cfd0ebc3abaf51ab57f5973d047d317c5cfa292880e52ce61222595e5e1daf41580943aff08a22b4aa2e32db025fb28c341521842f1bbeba8415be05b3298a4c8db3bd894dc8e82f68.png)
![list-4.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/556cf58fb094e61c00764138/125516c66e82c728ace21e0d46e49d8937cfd7ebc3abaf51ab57f5973d047d317c5cfa292880e52ce61222595e5e1daf41580943aff08a22b4aa2e32db025fb28c341521842f1bbebb8315be05b3298a4c8db3bd8845c7e92f68.png)
![report-upload-fail.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/556cf58fb094e61c00764138/125516c66e82c728ace21e0d46fa918a2c9097e49af9b34ca559bd92284f2b316546b3397f8fe62bab0021435a5747fe490d0910f5f98023a7b76f738a5c5dea82645c7dd42103eee9dc4be05ce36ade0d97bcae894dcae9392cee8a8c473b1f07118cfb4f78.png)
![SignUp-1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/556cf58fb094e61c00764138/125516c66e82c728ace21e0d46db9d9d2db793e4deabf301b44fff9e2c4533317346f6732987bb2db946225156574fad125b5f44aafeda22a5bf2e6c981e5ab38532022d8c6853beb2901cbe0bbb24824684b5b48f4dc3ea3d27f5c6.png)
![SignUp-2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/556cf58fb094e61c00764138/125516c66e82c728ace21e0d46db9d9d2db793e4ddabf301b44fff9e2c4533317346f6732987bb2db946225156574fad125b5f44aafeda22a5bf2e6c981e5ab38532022d8c6853beb2901cbe0bbb24824684b5b48f4dc3e93c23f5c6.png)
![SignUp-3.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/556cf58fb094e61c00764138/125516c66e82c728ace21e0d46db9d9d2db793e4dcabf301b44fff9e2c4533317346f6732987bb2db946225156574fad125b5f44aafeda22a5bf2e6c981e5ab38532022d8c6853beb2901db90bbb24824684b5b48f4dc3e93e27f5c6.png)

**Comment by tmfrnz** [comment]
- [ ] EntityForm should validate on submit (as AuthForm does already)
- [ ] Signin server error ("internal server error") not showing.

**Comment by tmfrnz** [comment]
see https://heydesigner.com/blog/write-perfect-error-message/

**Comment by tmfrnz** [comment]
common batch edit errors caused by outdated data:
- entity outdated 
- entity deleted
- connection already established (when making a connection)
- connection already deleted (when removing a connection)
