### ISSUE TITLE
Duplicate entries

### ISSUE THREAD

**Issue by tmfrnz** [impactoss/impactoss-client#418]
@ashbowe reported

> When I added in the thematic cluster: "Identify and Address Human Trafficking" it then added in 12/13 duplicates but just in draft form. None of the other participants had the text for that cluster so it couldn't have been multiple people.

**Comment by ashbowe** [comment]
In addition to creating c. 12 duplicates it also added over 100 recommendations to each cluster.

**Comment by tmfrnz** [comment]
Added a safe-guard to prevent multiple firing of form submit. This can prevent some duplication entries in the futures but there may be additional issues.

**Comment by tmfrnz** [comment]
@ashbowe the association with 100+ recommendations is very odd and I have yet to find out how and why this could have happened. Would you be able to provide a more detailed description of events or confirm and add to my description below? 

This is as I understand what happened (with questions):
- from the thematic cluster list you added a new cluster
- after saving the new cluster (title: "Identify and Address Human Trafficking", status: public (is this right?)), several (ca 12) duplicates (same title, status: draft) were also created and appeared in the thematic cluster list
- also in the thematic cluster list all or some of each (or some?) these newly created clusters appeared to have been associated with over 100 recommendations 
  - how much time passed between creating the cluster and noticing the linkages?
  - did all have the same number of recommendation associations?
 
thanks!

**Comment by ashbowe** [comment]
Hi Timo,

That is pretty much spot on. Unfortunately I was unable to look closely at what was actually happening as it was in the middle of the exercise I wass doing so I wass focused on making sure that went smoothly and getting rid of the duplicates. In any other environment I would have tried to look more closely at what was going on! 

Your recount of what I thought happened is accurate (and again I have to reiterate that it was a hectic environment so there may well be a totally non-bug related explanation, I just can't think of what I may have done or what someone else could have done to cause this).

In answer to your questions:

My recollection is that the cluster I created was public and the duplicates draft. I am almost certain of this as I remember noticing that was a differentiating feature when looking down the list. 

There was very little passage of time between creating the cluster and noticing the linkages and the duplicates, maybe a minute and that would have been the first opportunity I would have had to notice this. 

I am afraid I do not know if they all had the same number of recommendations, nor the precise number. 

Sorry I can't be more helpful! Do you want me to try to replicate what happened by going through the same process on the same laptop?

**Comment by tmfrnz** [comment]
Thank you @ashbowe this is very helpful. I am currently going through the 'versions' table of the database that also keeps track of any deleted items fortunately. I will post an update here very shortly...

**Comment by ashbowe** [comment]
Great work detective! 

And that's a great outcome, in that there is no bug and the possibility of multiple entries through clicking was already known.

Sorry for leading us down the wrong path. My recollection was such that the participants would not have been able to copy down what I wrote as the example on the screen but obviously I was wrong. I still have no idea what that user was playing at!! 

Warm regards,

Ash
